### ISSUE TITLE
Problem on pi zero W

### ISSUE THREAD

**Issue by TimBiernat** [AgilatechSystems/bme280#2]
Have been unable to get test working with bme280. bme280.py script finds device OK, but  I'd rather use node for this.
---
sudo python bme280.py
Chip ID     : 96
Version     : 0
Temperature :  24.65 C
Pressure :  983.553653199 hPa
Humidity :  46.2875792702 %
---
node -v v10.16.0
npm -v 6.9.0
git clone https://github.com/AgilatechSystems/bme280.git
npm install
npm test
  > @agilatech/bme280@0.10.0 test /home/tim/bme280
> mocha
  BME280
Bme280 ERROR: No valid chip ID response on register 208
Bme280 ERROR: No valid chip ID response on register 208
Bme280 ERROR: No valid chip ID response on register 208
Bme280 ERROR: No valid chip ID response on register 208
Bme280 ERROR: Could not initialize device on bus 1 at address 118

**Comment by AgilatechSystems** [comment]
Typically, that is what you'd see if the sensor was not connected on I2C bus 1 (i2c-1).  The default bus number is 1, but can be changed by passing an options object to the constructor like this -> `new Bme280({bus: 0});`

Is your sensor connected to I2C pins 3 and 5, or pins 27 and 28?  Pins 27 and 28 are bus 0.

If the bus is correct, then there could be an issue with the dependent i2c-bus module.

**Comment by AgilatechSystems** [comment]
Tested on RPi Zero W on bus 1. All tests passed.
