### ISSUE TITLE
BME280 not initializing on bus 1 - Raspberry Pi Zero W - NodeJs

### ISSUE THREAD

**Issue by RaposoHunter** [AgilatechSystems/bme280#6]
I followed step-by-step the tutorial on https://www.npmjs.com/package/@agilatech/bme280 but wasn't able to get any readings. 

The console outputs nothing to the prompt because the 'bme280' object itself isn't active. I made a simple loop to await for the initialization process but it just gets stuck in a infinite loop.

I wondered if you would have any idea of what's going on. The object is running without the additional options and the sensor is connected on pins 3 and 5. 

I tried another module and it worked just fine for I2C but I was hoping to use the SPI interface that your driver has.

What happens when I execute the program:

`pi@raspberrypi:~/Desktop/Node/bme280 $ node bme280`
`
pi@raspberrypi:~/Desktop/Node/bme280 $
`

**Comment by AgilatechSystems** [comment]
bme280 is not a standalone program. It is just a library. So 'node bme280' will simply load and initialize the class, but not produce any output.  Try running one of the programs in the 'examples' directory.
